language: node_js
node_js:
 - "node"
branches:
  only:
    - master
before_deploy:
  - npm run buildCss
  - npm run dist
  - cd dist
deploy:
  on:
    branch: master
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
